version: '3.9'
services:
  php-env:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql_db
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=root
      - MYSQL_DBNAME=cafecadastro
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafecadastro
    volumes:
      - ./cafecadastro.sql:/docker-entrypoint-initdb.d/cafecadastro.sql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db
